
project: 
  type: website
  
website: 
  page-navigation: true
  title: "Relatórios reprodutíveis com R" 
  site-url: "https://openscapes.github.io/quarto-website-tutorial" 
  repo-url: https://github.com/openscapes/quarto-website-tutorial 
  repo-actions: [edit, issue]
  
  page-footer:
    right: "This page is built with ❤️ and [Quarto](https://quarto.org/)."
    left: "&copy; CC-By Openscapes, 2024"
    background: "#D27B5A"
    
  sidebar:
    logo: "https://www.ime.usp.br/verao/assets/images/logo_verao.png"
    pinned: true
    background: "#D27B5A"
    align: center
    tools: 
      - icon: globe
        href: https://openscapes.org
        text: "Openscapes.org"
      - icon: github
        href: https://github.com/openscapes/quarto-website-tutorial
        text: "Quarto website tutorial"
      - icon: twitter
        href: https://twitter.com/openscapes
        text: "Openscapes Twitter"         

    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - href: index.qmd
      - href: https://cursosextensao.usp.br/course/view.php?id=3449
        text: "Plataforma USP"
      - section: "Sobre o curso"
        contents:
           - informacoes-gerais.qmd
           - profs.qmd
           - turma.qmd           
           - faq.qmd
      - section: "Materias"
        contents:
           - instrucoes-de-instalacao.qmd        
           - slides.qmd
           - trabalho_final.qmd
           - duvidas/index.qmd
      - section: "Aulas"
        contents:
          - aulas/aula-1.qmd
          - aulas/aula-2.qmd
          - aulas/aula-3.qmd
          - aulas/aula-4.qmd
          - aulas/aula-5.qmd
      - section: "Edições anteriores"
        contents:
          - href: https://beatrizmilz.github.io/2022-curso-de-verao-ime-usp-relatorios/programacao-do-curso.html
            text: "Edição 2022"
          - href: https://beatrizmilz.github.io/2023-curso-de-verao-ime-usp-relatorios/informacoes-gerais.html
            text: "Edição 2023"
          - href: https://beatrizmilz.github.io/2024-curso-de-verao-ime-usp-relatorios/slides.html
            text: "Edição 2024"
          - href: "https://beatrizmilz.github.io/2025-curso-de-verao-ime-usp-relatorios/slides.html"
            text: "Edição 2025"
      - licenca.qmd
format:
  html:
    theme: cosmo
    code-copy: true
    code-overflow: wrap
    toc: true

  
